language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.5
  - 5.6
  - hhvm
  - 7.0

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.1 WP_MULTISITE=0
  - WP_VERSION=4.0 WP_MULTISITE=0

install:
  - composer self-update
  - composer install

services:
  - elasticsearch

before_script:
  - sleep 10
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
